### ISSUE TITLE
Blackjack Module Processes Bets Below $0.01

### ISSUE THREAD

**Issue by jaredlyon** [KingWaffleshnoz/JareBot#4]
Users are able to submit extremely low values as a bet, allowing for an effectively nonexistent bet to be played.
![image](https://user-images.githubusercontent.com/29807461/54661900-2acc6200-4a99-11e9-83f6-da528c546ecf.png)

Additionally, users may submit certain small integer values (such as half a cent) which yield awkward returns.
![image](https://user-images.githubusercontent.com/29807461/54661980-7e3eb000-4a99-11e9-9bf0-739abd70a3f6.png)

**Comment by catamay** [comment]
In line 83 of `blackjack.js`, a simple fix for this would be to make bet equal to `Math.trunc(Number(msg.args[0])*100)/100;` 
(This just makes an output of some number 0.123456... to 0.12)
Then you can add whatever if statement required if the output above is zero (to prevent the minuscule bets issue.)

**Comment by jaredlyon** [comment]
Tested the following code:
```javascript
//initial bet
        if (msg.args[0] && isNaN(msg.args[0])) { 
          bet = 10;
          if (bot.bank[msg.author.id].balance.toFixed(2) < bet) {
            msg.channel.send("You frickin' foolian juulian, you don't have enough money to cover your bet!")
            return;
          } else {
            bot.bank[msg.author.id].balance -= bet
          }
        }
        else if (msg.args[0] && !isNaN(msg.args[0]) && Number(msg.args[0]) > 0) {
          bet = Number(msg.args[0]);
          if (bot.bank[msg.author.id].balance.toFixed(2) < bet) {
            msg.channel.send("You frickin' foolian juulian, you don't have enough money to cover your bet!")
            return;
          } else if (bet < 0.01) {
            msg.channel.send("You frickin' foolian juulian, you can't bet that amount!")
            return;
          } else {
            bot.bank[msg.author.id].balance -= bet
          }
        }
        else {
          bet = 10;
          if (bot.bank[msg.author.id].balance.toFixed(2) < bet) {
            msg.channel.send("You frickin' foolian juulian, you don't have enough money to cover your bet!")
            return;
          } else {
            bot.bank[msg.author.id].balance -= bet
          }
        }
```

Results:
![image](https://user-images.githubusercontent.com/29807461/54874835-49d83600-4db0-11e9-952b-54884b7030f7.png)

Will continue testing to prevent $0 bets from causing the bot to attempt setting a $10 bet amount. Currently, the bot is live with the above code, but a patch will not be pushed to GitHub until the aforementioned issue is also resolved.

**Comment by jaredlyon** [comment]
> In line 83 of `blackjack.js`, a simple fix for this would be to make bet equal to `Math.trunc(Number(msg.args[0])*100)/100;`
> (This just makes an output of some number 0.123456... to 0.12)
> Then you can add whatever if statement required if the output above is zero (to prevent the minuscule bets issue.)

Also note that a solution that involves the provided ```trunc()``` function would cause issue when rounding values close to zero:
![image](https://user-images.githubusercontent.com/29807461/54874909-8f493300-4db1-11e9-8aed-ef2869e74fdd.png)

The given ```trunc()``` function ultimately returns certain values back to zero, prompting the current bot architecture to reset the bet amount to $10 instead of exiting the process entirely. In my opinion, the easiest solution would be to just outright block all bets with values below $0.01, as the current architecture rounds the bet using a ```.toFixed(2)``` function at the end of the initial bet amount assignment.

**Comment by jaredlyon** [comment]
Eventually, I just rewrote the entire bet init process:
```javascript
//initial bet
        if (msg.args[0] && !isNaN(msg.args[0])) {
          bet = Number(msg.args[0]);
          if (bot.bank[msg.author.id].balance.toFixed(2) < bet) {
            msg.channel.send("You frickin' foolian juulian, you don't have enough money to cover your bet!")
            return;
          } else if (bet < 0.01) {
            msg.channel.send("You frickin' foolian juulian, you can't bet that amount!")
            return;
          } else {
            bot.bank[msg.author.id].balance -= bet
          }
        } else {
          bet = 10;
          if (bot.bank[msg.author.id].balance.toFixed(2) < bet) {
            msg.channel.send("You frickin' foolian juulian, you don't have enough money to cover your bet!")
            return;
          } else if (bet < 0.01) {
            msg.channel.send("You frickin' foolian juulian, you can't bet that amount!")
            return;
          } else {
            bot.bank[msg.author.id].balance -= bet
          }
        }
```

Results:
![image](https://user-images.githubusercontent.com/29807461/54886806-61afc880-4e49-11e9-8068-69dfc9a17854.png)
